# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2314c669fe416a78f3ea7399455311df7261f0b5f2be652b514f05ef47dcb8ce659842f3e221565a66085c97defc230a11b7d568fc0e1b794d0bb9dca2b03910

test:
  secret_key_base: 8008251fef82b5543d094bbd4d8817a4597b63a6501251900b86b3626dc6d63bb9ad7e7ee87125cf37e9a6d014be3dac08dce641b58555542e48809661a396a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
